#file: noinspection YAMLSchemaValidation
blank_issues_enabled: true
contact_links:
    # - name: Sprint to Milestone Planning
    #  url: https://github.com/iPoetDev/dash-and-do-github/milestones
    #  about: Project Planning & Organisation
    # - name: Agile Projects Tool
    #  url: https://github.com/iPoetDev/dash-and-do-github/projects
    #  about: Agile Tool for Epics & User Stories per Sprint
    - name: Technical Wiki
      url: https://github.com/iPoetDev/ibm-skills-ai-colab-sessions/wiki
      about: "Technical Wiki: Getting Started & Requirments"
    # - name: Repository Discussions
    #  url: https://github.com/iPoetDev/dash-and-do-github/discussions
    #  about: Open forum and contact point
    - name: GitHub Community Support
      url: https://github.com/orgs/community/discussions
      about: Please ask and answer questions here.
    - name: GitHub Security Bug Bounty
      url: https://bounty.github.com/
      about: Please report security vulnerabilities here.
